// WhatsApp Report Generation
class WhatsAppReport {
  static generateDailyReport(date = null) {
    const targetDate = date || new Date();
    const dateStr = targetDate.toISOString().split('T')[0];
    
    const orders = Storage.getOrders();
    const dayOrders = orders.filter(order => 
      order.date.startsWith(dateStr)
    );

    if (dayOrders.length === 0) {
      return null;
    }

    const totalRevenue = dayOrders.reduce((sum, order) => sum + order.total, 0);
    const totalOrders = dayOrders.length;
    const avgOrderValue = totalRevenue / totalOrders;

    // Payment mode summary
    const paymentModes = {};
    dayOrders.forEach(order => {
      paymentModes[order.paymentMode] = (paymentModes[order.paymentMode] || 0) + 1;
    });

    // Top selling items
    const itemCounts = {};
    dayOrders.forEach(order => {
      order.items.forEach(item => {
        itemCounts[item.name] = (itemCounts[item.name] || 0) + item.qty;
      });
    });

    const topItems = Object.entries(itemCounts)
      .map(([name, count]) => ({ name, count }))
      .sort((a, b) => b.count - a.count)
      .slice(0, 5);

    const settings = Storage.getSettings();
    const currency = settings?.currency || '₹';

    // Format date
    const formattedDate = targetDate.toLocaleDateString('en-IN', {
      weekday: 'long',
      year: 'numeric',
      month: 'long',
      day: 'numeric'
    });

    // Generate report text
    let report = `📊 *Daily Sales Report*\n`;
    report += `📅 ${formattedDate}\n\n`;
    report += `💰 *Total Revenue:* ${currency} ${totalRevenue.toFixed(2)}\n`;
    report += `📦 *Total Orders:* ${totalOrders}\n`;
    report += `📈 *Average Order Value:* ${currency} ${avgOrderValue.toFixed(2)}\n\n`;

    report += `💳 *Payment Summary:*\n`;
    Object.entries(paymentModes).forEach(([mode, count]) => {
      report += `  • ${mode.toUpperCase()}: ${count}\n`;
    });
    report += `\n`;

    if (topItems.length > 0) {
      report += `🏆 *Top 5 Selling Items:*\n`;
      topItems.forEach((item, index) => {
        report += `  ${index + 1}. ${item.name} - ${item.count} sold\n`;
      });
    }

    report += `\n---\n`;
    report += `Generated by Restaurant POS System`;

    return report;
  }

  static async generateAndSend() {
    const settings = Storage.getSettings();
    const whatsappNumber = settings?.whatsappNumber;

    if (!whatsappNumber) {
      App.showToast('WhatsApp number not configured in settings', 'error');
      return;
    }

    const report = this.generateDailyReport();
    if (!report) {
      App.showToast('No sales data for today', 'error');
      return;
    }

    // Try to send via API first, fallback to WhatsApp Web
    const apiKey = settings?.whatsappApiKey;
    const apiService = settings?.whatsappApiService || 'wasend'; // wasend, twilio, or custom
    const apiUrl = settings?.whatsappApiUrl;

    if (apiKey && apiService !== 'web') {
      try {
        const sent = await this.sendViaAPI(whatsappNumber, report, apiKey, apiService, apiUrl);
        if (sent) {
          App.showToast('Report sent successfully via WhatsApp!', 'success');
          return;
        }
      } catch (error) {
        console.error('API send failed:', error);
        App.showToast('API send failed, opening WhatsApp Web...', 'error');
        // Fall through to WhatsApp Web
      }
    }

    // Fallback to WhatsApp Web
    this.sendViaWhatsAppWeb(whatsappNumber, report);
  }

  static async sendViaAPI(whatsappNumber, message, apiKey, service = 'wasend', apiUrl = null) {
    // Format WhatsApp number (remove + and spaces, ensure country code)
    let cleanNumber = whatsappNumber.replace(/[+\s-]/g, '');
    
    // Add country code if not present (India: +91)
    if (!cleanNumber.startsWith('91') && cleanNumber.length === 10) {
      cleanNumber = '91' + cleanNumber;
    }

    try {
      if (service === 'wasend') {
        // WASend API integration
        const response = await fetch('https://api.wasend.dev/send', {
          method: 'POST',
          headers: {
            'Content-Type': 'application/json',
            'Authorization': `Bearer ${apiKey}`
          },
          body: JSON.stringify({
            number: cleanNumber,
            message: message
          })
        });

        if (response.ok) {
          const data = await response.json();
          return data.success !== false; // Return true if success is not explicitly false
        } else {
          const errorData = await response.json().catch(() => ({}));
          throw new Error(errorData.message || `API Error: ${response.status}`);
        }
      } else if (service === 'twilio') {
        // Twilio WhatsApp API (requires backend proxy for security)
        const response = await fetch('/api/whatsapp/send', {
          method: 'POST',
          headers: {
            'Content-Type': 'application/json'
          },
          body: JSON.stringify({
            to: `whatsapp:+${cleanNumber}`,
            message: message,
            apiKey: apiKey
          })
        });

        if (response.ok) {
          return true;
        } else {
          throw new Error(`API Error: ${response.status}`);
        }
      } else if (service === 'custom') {
        // Custom API endpoint
        const customUrl = apiUrl || Storage.getSettings()?.whatsappApiUrl || '/api/whatsapp/send';
        const response = await fetch(customUrl, {
          method: 'POST',
          headers: {
            'Content-Type': 'application/json',
            'Authorization': `Bearer ${apiKey}`
          },
          body: JSON.stringify({
            number: cleanNumber,
            message: message
          })
        });

        if (response.ok) {
          return true;
        } else {
          throw new Error(`API Error: ${response.status}`);
        }
      }
    } catch (error) {
      console.error('WhatsApp API Error:', error);
      throw error;
    }

    return false;
  }

  static sendViaWhatsAppWeb(whatsappNumber, message) {
    // Format WhatsApp number (remove + and spaces)
    const cleanNumber = whatsappNumber.replace(/[+\s]/g, '');
    
    // Create WhatsApp URL
    const encodedMessage = encodeURIComponent(message);
    const whatsappURL = `https://wa.me/${cleanNumber}?text=${encodedMessage}`;

    // Open WhatsApp
    window.open(whatsappURL, '_blank');
    App.showToast('Opening WhatsApp...', 'success');
  }

  static setupAutoReport() {
    const settings = Storage.getSettings();
    
    // Default WhatsApp number
    const defaultWhatsAppNumber = '6383170709';
    const defaultReportTime = '22:00'; // 10 PM
    
    // Use settings or defaults
    const whatsappNumber = settings?.whatsappNumber || defaultWhatsAppNumber;
    const reportTime = settings?.reportTime || defaultReportTime;
    const autoReportEnabled = settings?.autoReportEnabled !== false; // Default to true
    
    if (!autoReportEnabled) {
      console.log('Auto-report is disabled');
      return;
    }

    // Parse report time
    const [hours, minutes] = reportTime.split(':').map(Number);
    
    // Check every minute if it's time to send
    const checkInterval = setInterval(() => {
      const now = new Date();
      const currentHour = now.getHours();
      const currentMinute = now.getMinutes();
      
      // Check if it's the report time (within the same minute)
      if (currentHour === hours && currentMinute === minutes) {
        // Check if we already sent today's report
        const lastReportDate = localStorage.getItem('last_auto_report_date');
        const today = now.toISOString().split('T')[0];
        
        if (lastReportDate !== today) {
          console.log('Sending auto-report...');
          this.sendAutoReport(whatsappNumber);
          localStorage.setItem('last_auto_report_date', today);
        }
      }
    }, 60000); // Check every minute

    // Store interval ID to clear if needed
    window.autoReportInterval = checkInterval;
    
    console.log(`Auto-report enabled - will send daily at ${reportTime} to ${whatsappNumber}`);
  }

  static async sendAutoReport(whatsappNumber) {
    const report = this.generateDailyReport();
    if (!report) {
      console.log('No sales data for today - skipping auto-report');
      this.sendNotification('Daily Report', 'No sales data available for today');
      return;
    }

    const settings = Storage.getSettings();
    const apiKey = settings?.whatsappApiKey;
    const apiService = settings?.whatsappApiService || 'wasend';
    const apiUrl = settings?.whatsappApiUrl;

    // Try to send via API first
    if (apiKey && apiService !== 'web') {
      try {
        const sent = await this.sendViaAPI(whatsappNumber, report, apiKey, apiService, apiUrl);
        if (sent) {
          this.sendNotification('Daily Report Sent', 'Daily sales report sent successfully via WhatsApp!');
          console.log('Auto-report sent via API');
          return;
        }
      } catch (error) {
        console.error('Auto-report API send failed:', error);
        // Fall through to WhatsApp Web
      }
    }

    // Fallback to WhatsApp Web
    this.sendNotification('Daily Report Ready', 'Daily sales report is ready. Opening WhatsApp...');
    setTimeout(() => {
      this.sendViaWhatsAppWeb(whatsappNumber, report);
      console.log('Auto-report opened in WhatsApp');
    }, 1000);
  }

  static requestNotificationPermission() {
    if ('Notification' in window && Notification.permission === 'default') {
      Notification.requestPermission();
    }
  }

  static sendNotification(title, body) {
    if ('Notification' in window && Notification.permission === 'granted') {
      new Notification(title, {
        body: body,
        icon: '/assets/icon-192.png'
      });
    }
  }
}

// Setup auto-report on page load
document.addEventListener('DOMContentLoaded', () => {
  WhatsAppReport.setupAutoReport();
  WhatsAppReport.requestNotificationPermission();
});

